project_name: kopano-ld

builds:
- env:
  - CGO_ENABLED=0

  main: ./kopano-ld.go

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

sign:
  artifacts: checksum

nfpm:
  homepage: https://github.com/nupplaphil/kopano-ldap

  maintainer: Philipp Holzer <admin@philipp.info>

  description: LDAP Command Line Interface for Kopano

  license: Apache 2.0

  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

  formats:
    - deb
    - rpm

  bindir: /usr/bin
