language: go

sudo: required

services:
  - docker

matrix:
  include:
  - go: 1.9.4
  - go: 1.10.0
  - go: tip
  allow_failures:
  - go: tip

before_install:
  - docker pull nupplaphil/kopano-ldap
  - docker run -d -p 127.0.0.1:389:389 nupplaphil/kopano-ldap
  - docker ps -a
  - go get -t -v ./...

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
